In [15]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier

In [2]:
X_train = pd.read_csv('data/X_train.csv')
y_train = pd.read_csv('data/y_train.csv').values.ravel()
X_test = pd.read_csv('data/X_test.csv')
y_test = pd.read_csv('data/y_test.csv').values.ravel()

# Baseline

## XGBoosting
Best performer from classification trials

In [20]:
xgb_0 = XGBClassifier(max_depth=5)
xgb_0.fit(X_train,y_train).score(X_test, y_test)

0.8484486873508353

In [22]:
importances = pd.concat([pd.DataFrame(X_train.columns),
                         pd.DataFrame(np.transpose(xgb_0.feature_importances_))], 
                        axis = 1)
importances

           0         0
0     gender  0.023205
1        age  0.034580
2      age_o  0.000000
3   int_corr  0.019367
4   samerace  0.020384
5       date  0.028621
6   exphappy  0.019852
7    attr3_1  0.025507
8    sinc3_1  0.025202
9     fun3_1  0.023922
10  intel3_1  0.030892
11    amb3_1  0.023705
12      attr  0.065720
13      sinc  0.021198
14     intel  0.017477
15       fun  0.128401
16       amb  0.018292
17      shar  0.053193
18   attr1_1  0.026491
19   sinc1_1  0.029196
20  intel1_1  0.029101
21    fun1_1  0.018268
22    amb1_1  0.029117
23   shar1_1  0.025221
24  pf_o_att  0.021762
25  pf_o_sin  0.020367
26  pf_o_int  0.028417
27  pf_o_fun  0.019857
28  pf_o_amb  0.023588
29  pf_o_sha  0.024130
30  goal_2.0  0.030342
31  goal_3.0  0.021162
32  goal_4.0  0.018864
33  goal_5.0  0.027385
34  goal_6.0  0.027214
35  goal_nan  0.000000

## Logistic Regression

In [23]:
lr_0 = LogisticRegression(max_iter=3000, penalty='l2', solver='sag')
lr_0.fit(X_train,y_train).score(X_train, y_train)

0.8390032826022082

# Manual Trials
## Without Preferences

In [5]:
X_train_2 = X_train.drop(X_train.loc[:,'attr1_1':'pf_o_sha'].head(0).columns, axis=1)
X_test_2 = X_test.drop(X_test.loc[:,'attr1_1':'pf_o_sha'].head(0).columns, axis=1)

In [6]:
xgb = XGBClassifier(max_depth=5)
xgb.fit(X_train_2,y_train).score(X_test_2, y_test)

0.8430787589498807

In [7]:
lr = LogisticRegression(max_iter=3000, penalty='l2', solver='sag')
lr.fit(X_train_2,y_train).score(X_test_2, y_test)

0.8347255369928401

## Without Gender

In [8]:
X_train_3 = X_train.drop(columns=['gender'])
X_test_3 = X_test.drop(columns=['gender'])

In [9]:
xgb = XGBClassifier(max_depth=5)
xgb.fit(X_train_3,y_train).score(X_test_3, y_test)

0.8496420047732697

In [10]:
lr = LogisticRegression(max_iter=3000, penalty='l2', solver='sag')
lr.fit(X_train_3,y_train).score(X_test_3, y_test)

0.8359188544152745

# L1 Regularization
## Logistic Regression

In [11]:
# params = {'penalty': ['l1'],
#           'solver': ['liblinear', 'saga'],
#           'max_iter': [3000]}

# gscv = GridSearchCV(LogisticRegression(), params, cv=3)
# gscv.fit(X_train, y_train)
# gscv.best_params_

In [12]:
lr = LogisticRegression(max_iter=3000, penalty='l1', solver='saga')
lr.fit(X_train,y_train).score(X_train, y_train)

0.838704864219636

In [13]:
lr.score(X_test, y_test)

0.8347255369928401

In [16]:
coefficients = pd.concat([pd.DataFrame(X_train.columns),
                          pd.DataFrame(np.transpose(lr.coef_))], 
                         axis = 1)
coefficients

           0         0
0     gender -0.227981
1        age -0.018837
2      age_o -0.018837
3   int_corr  0.196187
4   samerace -0.054904
5       date -0.117895
6   exphappy -0.023227
7    attr3_1  0.076634
8    sinc3_1  0.013839
9     fun3_1 -0.032163
10  intel3_1 -0.110431
11    amb3_1 -0.014234
12      attr  0.243701
13      sinc  0.014743
14     intel  0.056835
15       fun  0.257979
16       amb -0.130023
17      shar  0.212471
18   attr1_1 -0.018441
19   sinc1_1 -0.029062
20  intel1_1 -0.003180
21    fun1_1 -0.001129
22    amb1_1 -0.019844
23   shar1_1 -0.026678
24  pf_o_att -0.021596
25  pf_o_sin -0.020751
26  pf_o_int -0.011430
27  pf_o_fun -0.009461
28  pf_o_amb -0.022629
29  pf_o_sha -0.024598
30  goal_2.0 -0.027615
31  goal_3.0 -0.232992
32  goal_4.0 -0.035758
33  goal_5.0  0.018012
34  goal_6.0 -0.285382
35  goal_nan  0.049501

## XGBoost

In [19]:
params = {'n_estimators': [100, 150, 200],
          'max_depth': [3, 5, 10],
          'reg_alpha': [1]}

gscv = GridSearchCV(XGBClassifier(), params, cv=3)
gscv.fit(X_train, y_train)
gscv.best_params_

{'max_depth': 5, 'n_estimators': 100, 'reg_alpha': 1}

In [24]:
xgb = XGBClassifier(max_depth=5, reg_alpha=1)
xgb.fit(X_train,y_train).score(X_test, y_test)

0.8490453460620525

In [26]:
importances = pd.concat([pd.DataFrame(X_train.columns),
                         pd.DataFrame(np.transpose(xgb.feature_importances_))], 
                        axis = 1,
                        )
importances

           0         0
0     gender  0.037612
1        age  0.027325
2      age_o  0.000000
3   int_corr  0.017860
4   samerace  0.019479
5       date  0.031868
6   exphappy  0.018051
7    attr3_1  0.023444
8    sinc3_1  0.021474
9     fun3_1  0.020442
10  intel3_1  0.024570
11    amb3_1  0.023476
12      attr  0.066723
13      sinc  0.021155
14     intel  0.016669
15       fun  0.132156
16       amb  0.017204
17      shar  0.051366
18   attr1_1  0.024020
19   sinc1_1  0.026462
20  intel1_1  0.028193
21    fun1_1  0.025801
22    amb1_1  0.025999
23   shar1_1  0.025476
24  pf_o_att  0.020622
25  pf_o_sin  0.020317
26  pf_o_int  0.026087
27  pf_o_fun  0.021991
28  pf_o_amb  0.024152
29  pf_o_sha  0.024782
30  goal_2.0  0.025577
31  goal_3.0  0.026135
32  goal_4.0  0.016613
33  goal_5.0  0.024271
34  goal_6.0  0.042626
35  goal_nan  0.000000